
services:
  app:
    build: ./app/
    image: diplo-api:latest
    restart: unless-stopped
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - ml_service_network
  database:
    image: postgres:16
    env_file:
      - ./app/.env
    ports:
      - 5555:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - ml_service_network
  web-proxy:
#    image: nginx:latest
    container_name: diplo-service-nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - ml_service_network
volumes:
    postgres_volume:
networks:
  ml_service_network:
    name: ml_service_network
    driver: bridge



